# Generated by Django 4.1.2 on 2022-11-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agent',
            table='agent_profile',
        ),
    ]
