# Generated by Django 4.1.2 on 2022-12-01 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_agent_facebook_alter_agent_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('Area', models.CharField(max_length=10)),
                ('bedroom', models.CharField(blank=True, max_length=10)),
                ('bathroom', models.CharField(blank=True, max_length=10)),
                ('garage', models.CharField(blank=True, max_length=10)),
                ('video', models.CharField(blank=True, max_length=250)),
                ('floor_plan', models.ImageField(blank=True, upload_to='')),
                ('ubication', models.CharField(blank=True, max_length=250)),
                ('price', models.CharField(blank=True, max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.agent')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(1, 'House'), (2, 'Office Space')], default='House', max_length=20)),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(1, 'Sale'), (2, 'Sold'), (3, 'Rent')], default='Sales', max_length=20)),
                ('asset_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.CharField(max_length=20)),
                ('amenities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.property')),
            ],
        ),
    ]
