# Generated by Django 4.1.2 on 2022-12-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_property_propertytype_propertystatus_propertyamenity'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(choices=[(1, 'Florida'), (2, 'Alabama')], max_length=50, null=True),
        ),
    ]
