# Generated by Django 4.1.2 on 2022-12-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_property_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(choices=[(1, 'Alabama'), (2, 'California'), (3, 'Florida'), (4, 'Illinois'), (5, 'New York'), (6, 'Texas')], max_length=50, null=True),
        ),
    ]
