# Generated by Django 4.1.2 on 2022-12-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
