# Generated by Django 4.1.2 on 2022-12-01 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_property_state_alter_propertystatus_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyamenity',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='images',
        ),
        migrations.RemoveField(
            model_name='propertystatus',
            name='asset_status',
        ),
        migrations.RemoveField(
            model_name='propertytype',
            name='types',
        ),
        migrations.AddField(
            model_name='propertyamenity',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='project.property'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='project.property'),
        ),
        migrations.AddField(
            model_name='propertystatus',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_status', to='project.property'),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='project.property'),
        ),
    ]
